export default [
  {
    name: "Britons",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Age of Kings",
  },
  {
    name: "Byzantines",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Age of Kings",
  },
  {
    name: "Celts",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Age of Kings",
  },
  {
    name: "Chinese",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Age of Kings",
  },
  {
    name: "Franks",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Age of Kings",
  },
  {
    name: "Goths",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Age of Kings",
  },
  {
    name: "Japanese",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Age of Kings",
  },
  {
    name: "Mongols",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Age of Kings",
  },
  {
    name: "Persians",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Age of Kings",
  },
  {
    name: "Saracens",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Age of Kings",
  },
  {
    name: "Teutons",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Age of Kings",
  },
  {
    name: "Turks",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Age of Kings",
  },
  {
    name: "Vikings",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Age of Kings",
  },
  {
    name: "Aztecs",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Conquerors",
  },
  {
    name: "Huns",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Conquerors",
  },
  {
    name: "Koreans",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Conquerors",
  },
  {
    name: "Mayans",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Conquerors",
  },
  {
    name: "Spanish",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Conquerors",
  },
  {
    name: "Incas",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Forgotten",
  },
  {
    name: "Indians",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Forgotten",
  },
  {
    name: "Italians",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Forgotten",
  },
  {
    name: "Magyars",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Forgotten",
  },
  {
    name: "Slavs",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "The Forgotten",
  },
  {
    name: "Berbers",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "Rise of the Rajas",
  },
  {
    name: "Ethiopians",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "Rise of the Rajas",
  },
  {
    name: "Malians",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "Rise of the Rajas",
  },
  {
    name: "Portuguese",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "Rise of the Rajas",
  },
  {
    name: "Bulgarians",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "Definitive Edition",
  },
  {
    name: "Cumans",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "Definitive Edition",
  },
  {
    name: "Lithuanians",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "Definitive Edition",
  },
  {
    name: "Tatars",
    wasSelectedBefore: false,
    isIncluded: true,
    dlc: "Definitive Edition",
  },
];
