let civs = [
  {
    name: "Britons",
    wasSelectedBefore: false,
    gotoUnit: ["archers"],
    isIncluded: true,
    dlc: "The Age of Kings",
    lastPicked: null,
    icon: "icons/Britons.png",
  },
  {
    name: "Byzantines",
    wasSelectedBefore: false,
    gotoUnit: ["archers", "navy"],
    isIncluded: true,
    dlc: "The Age of Kings",
    lastPicked: null,
    icon: "icons/Byzantines.png",
  },
  {
    name: "Celts",
    wasSelectedBefore: false,
    gotoUnit: ["infantry", "siege"],
    isIncluded: true,
    dlc: "The Age of Kings",
    lastPicked: null,
    icon: "icons/Celts.png",
  },
  {
    name: "Chinese",
    wasSelectedBefore: false,
    gotoUnit: ["archers"],
    isIncluded: true,
    dlc: "The Age of Kings",
    lastPicked: null,
    icon: "icons/Chinese.png",
  },
  {
    name: "Franks",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry"],
    isIncluded: true,
    dlc: "The Age of Kings",
    lastPicked: null,
    icon: "icons/Franks.png",
  },
  {
    name: "Goths",
    wasSelectedBefore: false,
    gotoUnit: ["infantry"],
    isIncluded: true,
    dlc: "The Age of Kings",
    lastPicked: null,
    icon: "icons/Goths.png",
  },
  {
    name: "Japanese",
    wasSelectedBefore: false,
    gotoUnit: ["infantry", "archers"],
    isIncluded: true,
    dlc: "The Age of Kings",
    lastPicked: null,
    icon: "icons/Japanese.png",
  },
  {
    name: "Mongols",
    wasSelectedBefore: false,
    gotoUnit: ["archers", "siege"],
    isIncluded: true,
    dlc: "The Age of Kings",
    lastPicked: null,
    icon: "icons/Mongols.png",
  },
  {
    name: "Persians",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry"],
    isIncluded: true,
    dlc: "The Age of Kings",
    lastPicked: null,
    icon: "icons/Persians.png",
  },
  {
    name: "Saracens",
    wasSelectedBefore: false,
    gotoUnit: ["archers", "navy"],
    isIncluded: true,
    dlc: "The Age of Kings",
    lastPicked: null,
    icon: "icons/Saracens.png",
  },
  {
    name: "Teutons",
    wasSelectedBefore: false,
    gotoUnit: ["infantry", "cavalry", "siege"],
    isIncluded: true,
    dlc: "The Age of Kings",
    lastPicked: null,
    icon: "icons/Teutons.png",
  },
  {
    name: "Turks",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry", "archers"],
    isIncluded: true,
    dlc: "The Age of Kings",
    lastPicked: null,
    icon: "icons/Turks.png",
  },
  {
    name: "Vikings",
    wasSelectedBefore: false,
    gotoUnit: ["infantry", "archers", "navy"],
    isIncluded: true,
    dlc: "The Age of Kings",
    lastPicked: null,
    icon: "icons/Vikings.png",
  },
  {
    name: "Aztecs",
    wasSelectedBefore: false,
    gotoUnit: ["infantry", "eagles", "monks", "archers"],
    isIncluded: true,
    dlc: "The Conquerors",
    lastPicked: null,
    icon: "icons/Aztecs.png",
  },
  {
    name: "Huns",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry"],
    isIncluded: true,
    dlc: "The Conquerors",
    lastPicked: null,
    icon: "icons/Huns.png",
  },
  {
    name: "Koreans",
    wasSelectedBefore: false,
    gotoUnit: ["archers", "siege", "navy"],
    isIncluded: true,
    dlc: "The Conquerors",
    lastPicked: null,
    icon: "icons/Koreans.png",
  },
  {
    name: "Mayans",
    wasSelectedBefore: false,
    gotoUnit: ["eagles", "archers"],
    isIncluded: true,
    dlc: "The Conquerors",
    lastPicked: null,
    icon: "icons/Mayans.png",
  },
  {
    name: "Spanish",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry", "monks", "navy"],
    isIncluded: true,
    dlc: "The Conquerors",
    lastPicked: null,
    icon: "icons/Spanish.png",
  },
  {
    name: "Incas",
    wasSelectedBefore: false,
    gotoUnit: ["archers", "eagles"],
    isIncluded: true,
    dlc: "The Forgotten",
    lastPicked: null,
    icon: "icons/Incas.png",
  },
  {
    name: "Indians",
    altName: "Hindustanis",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry"],
    isIncluded: true,
    dlc: "The Forgotten",
    lastPicked: null,
    icon: "icons/Hindustanis.png",
  },
  {
    name: "Italians",
    wasSelectedBefore: false,
    gotoUnit: ["archers", "navy"],
    isIncluded: true,
    dlc: "The Forgotten",
    lastPicked: null,
    icon: "icons/Italians.png",
  },
  {
    name: "Magyars",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry", "archers"],
    isIncluded: true,
    dlc: "The Forgotten",
    lastPicked: null,
    icon: "icons/Magyars.png",
  },
  {
    name: "Slavs",
    wasSelectedBefore: false,
    gotoUnit: ["infantry", "cavalry", "siege"],
    isIncluded: true,
    dlc: "The Forgotten",
    lastPicked: null,
    icon: "icons/Slavs.png",
  },
  {
    name: "Berbers",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry", "navy"],
    isIncluded: true,
    dlc: "The African Kindoms",
    lastPicked: null,
    icon: "icons/Berbers.png",
  },
  {
    name: "Ethiopians",
    wasSelectedBefore: false,
    gotoUnit: ["archers", "siege"],
    isIncluded: true,
    dlc: "The African Kindoms",
    lastPicked: null,
    icon: "icons/Ethiopians.png",
  },
  {
    name: "Malians",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry", "infantry"],
    isIncluded: true,
    dlc: "The African Kindoms",
    lastPicked: null,
    icon: "icons/Malians.png",
  },
  {
    name: "Portuguese",
    wasSelectedBefore: false,
    gotoUnit: ["archers", "navy"],
    isIncluded: true,
    dlc: "The African Kindoms",
    lastPicked: null,
    icon: "icons/Portugese.png",
  },
  {
    name: "Burmese",
    wasSelectedBefore: false,
    gotoUnit: ["monks"],
    isIncluded: true,
    dlc: "Rise of the Rajas",
    lastPicked: null,
    icon: "icons/Burmese.png",
  },
  {
    name: "Khmer",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry", "archers"],
    isIncluded: true,
    dlc: "Rise of the Rajas",
    lastPicked: null,
    icon: "icons/Khmer.png",
  },
  {
    name: "Malay",
    wasSelectedBefore: false,
    gotoUnit: ["archers"],
    isIncluded: true,
    dlc: "Rise of the Rajas",
    lastPicked: null,
    icon: "icons/Malay.png",
  },
  {
    name: "Vietnamese",
    wasSelectedBefore: false,
    gotoUnit: ["archers"],
    isIncluded: true,
    dlc: "Rise of the Rajas",
    lastPicked: null,
    icon: "icons/Vietnamese.png",
  },
  {
    name: "Bulgarians",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry", "infantry"],
    isIncluded: true,
    dlc: "Definitive Edition",
    lastPicked: null,
    icon: "icons/Bulgarians.png",
  },
  {
    name: "Cumans",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry"],
    isIncluded: true,
    dlc: "Definitive Edition",
    lastPicked: null,
    icon: "icons/Cumans.png",
  },
  {
    name: "Lithuanians",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry", "monks"],
    isIncluded: true,
    dlc: "Definitive Edition",
    lastPicked: null,
    icon: "icons/Lithuanians.png",
  },
  {
    name: "Tatars",
    wasSelectedBefore: false,
    gotoUnit: ["archers", "cavalry"],
    isIncluded: true,
    dlc: "Definitive Edition",
    lastPicked: null,
    icon: "icons/Tatars.png",
  },
  {
    name: "Burgundians",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry"],
    isIncluded: true,
    dlc: "Lords of the West",
    lastPicked: null,
    icon: "icons/Burgundians.png",
  },
  {
    name: "Sicilians",
    wasSelectedBefore: false,
    gotoUnit: ["archers", "infantry"],
    isIncluded: true,
    dlc: "Lords of the West",
    lastPicked: null,
    icon: "icons/Sicilians.png",
  },
  {
    name: "Poles",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry"],
    isIncluded: true,
    dlc: "Dawn of the Dukes",
    lastPicked: null,
    icon: "icons/Poles.png",
  },
  {
    name: "Bohemians",
    wasSelectedBefore: false,
    gotoUnit: ["monks", "siege", "archers"],
    isIncluded: true,
    dlc: "Dawn of the Dukes",
    lastPicked: null,
    icon: "icons/Bohemians.png",
  },
  {
    name: "Bengalis",
    wasSelectedBefore: false,
    gotoUnit: ["navy"],
    isIncluded: true,
    dlc: "Dynasties of India",
    lastPicked: null,
    icon: "icons/Bengalis.png",
  },
  {
    name: "Dravidians",
    wasSelectedBefore: false,
    gotoUnit: ["infantry", "navy"],
    isIncluded: true,
    dlc: "Dynasties of India",
    lastPicked: null,
    icon: "icons/Dravidians.png",
  },
  {
    name: "Gurjaras",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry"],
    isIncluded: true,
    dlc: "Dynasties of India",
    lastPicked: null,
    icon: "icons/Gurjaras.png",
  },
  {
    name: "Romans",
    wasSelectedBefore: false,
    gotoUnit: ["infantry"],
    isIncluded: true,
    dlc: "Return of Rome",
    lastPicked: null,
    icon: "icons/Romans.png",
  },
  {
    name: "Armenians",
    wasSelectedBefore: false,
    gotoUnit: ["infantry", "navy"],
    isIncluded: true,
    dlc: "The Mountain Royals",
    lastPicked: null,
    icon: "icons/Armenians.png",
  },
  {
    name: "Georgians",
    wasSelectedBefore: false,
    gotoUnit: ["cavalry"],
    isIncluded: true,
    dlc: "The Mountain Royals",
    lastPicked: null,
    icon: "icons/Georgians.png",
  },
];

civs.map(
  (c) => (c.wikiLink = "https://ageofempires.fandom.com/wiki/" + c.name)
);

let unitStrats = new Set();
for (let c of civs) {
  for (let u of c.gotoUnit) {
    unitStrats.add(u);
  }
}

export const civilizations = civs;
export const unitStrategies = Array.from(unitStrats);
